<a href="https://colab.research.google.com/github/IRISPHAM3112/AIO-M1/blob/main/M1_W3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Exe1
import torch
import torch.nn as nn
class Softmax(nn.Module):
  def __init__(self):
    #Khoi tao lop con tu nn.Module
    super(Softmax, self).__init__()
  def forward(self, x):
    e_x = torch.exp(x)
    return e_x/torch.sum(e_x)
  def softmax_stable(self,x ):
    e_x = torch.exp(x-torch.max(x))
    return e_x/torch.sum(e_x)

data = torch.Tensor([1,2,3])
softmax = Softmax()
output = softmax(data)
print(output)
output_stable = softmax.softmax_stable(data)
output_stable
print(output_stable)

tensor([0.0900, 0.2447, 0.6652])
tensor([0.0900, 0.2447, 0.6652])


In [ ]:
#Exe2
class Person():
  def __init__(self, name, yob):
    self.name = name
    self.yob = yob
  def add_person(object_list, person):
    object_list.append(person)
  def describe(self):
    print(self.name, self.yob)
class Student(Person):
  def __init__(self, name, yob, grade):
    super().__init__(name, yob)
    self.grade = grade
  def describe(self):
    print(self.name, self.yob, self.grade)
class Teacher(Person):
  def __init__(self, name, yob, subject):
    super().__init__(name, yob)
    self.subject = subject
  def describe(self):
    print(self.name, self.yob, self.subject)

class Doctor(Person):
  def __init__(self, name, yob, specialist):
    super().__init__(name, yob)
    self.specialist = specialist
  def describe(self):
    print(self.name, self.yob, self.specialist)



class Ward:
  def __init__(self, ward_name):
    self.ward_name = ward_name
    self.people = []
  def add_person(self, person):
    self.people.append(person)
  def describe(self):
    print(self.ward_name)
    for person in self.people:
      person.describe()
  def count_doctor(self):
    count = 0
    for person in self.people:
      if isinstance(person, Doctor):
        count+=1
    return count
  def sort_age(self):
    age_list = [person.yob for person in self.people]
    age_list.sort()
    return age_list
  def compute_average_age(self):
    age_teacher = [person.yob for person in self.people if isinstance(person, Teacher)]
    average_age = sum(age_teacher)/len(age_teacher)
    return average_age

student1 = Student(name = "Toan", yob = 2003, grade = "7")
teacher1 = Teacher( name ="teacherA", yob =1969 , subject =" Math ")


doctor1 = Doctor( name ="doctorA", yob =1945 , specialist =" Endocrinologists ")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")
teacher3 = Teacher(name="teacherC", yob=1995, subject="English")
ward1 = Ward(ward_name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.add_person(teacher3)
ward1.describe()

ward1.count_doctor()
ward1.sort_age()
ward1.compute_average_age()

Ward1
Toan 2003 7
teacherA 1969  Math 
teacherB 1995 History
doctorA 1945  Endocrinologists 
doctorB 1975 Cardiologists
teacherC 1995 English


1986.3333333333333

In [ ]:
#Exe 3
class MyStack:
  def __init__(self, capacity):
    self.capacity = capacity
    self.stack = []
  def is_empty(self):
    if len(self.stack) == 0:
      return True
    else:
      return False
  def is_full(self):
    return len(self.stack) == self.capacity
  def pop(self):
    if not self.is_empty():
      return self.stack.pop()
    else:
      return IndexError("pop from empty stack")
  def push(self, value):
    if not self.is_full():
      self.stack.append(value)
    else:
      raise IndexError("push to full stack ")
  def top(self):
    if not self.is_empty():
      return self.stack[-1]
    else:
      raise IndexError("top from empty stack")
stack1 = MyStack(capacity=5)

stack1.push(1)

stack1.push(2)

print(stack1.is_full())
# >> False

print(stack1.top())
# >> 2

print(stack1.pop())
# >> 2

print(stack1.top())
# >> 1

print(stack1.pop())
# >> 1

print(stack1.is_empty())
# >> True


False
2
2
1
1
True


In [ ]:
#Exe 4
class MyQueue:
  def __init__(self, capacity):
    self.capacity = capacity
    self.queue = []
  def is_empty(self):
    return len(self.queue) == 0
  def is_full(self):
    return len(self.queue) == self.capacity
  def dequeue(self):
    if not self.is_empty():
      return self.queue.pop(0)
    else:
      raise IndexError("Dequeue from empty queue")
  def enqueue(self, value):
    if not self.is_full():
      self.queue.append(value)
    else:
      raise IndexError("Enqueue from empty queue")

  def front(self):
    return self.queue[0]
queue1 = MyQueue(capacity=5)

queue1.enqueue(1)
queue1.enqueue(2)

print(queue1.is_full())
# >> False

print(queue1.front())
# >> 1

print(queue1.dequeue())
# >> 1

print(queue1.front())
# >> 2

print(queue1.dequeue())
# >> 2

print(queue1.is_empty())
# >> True


False
1
1
2
2
True


# Phần code câu hỏi trắc nghiệm

In [ ]:
#exe2
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        e_x = torch.exp(x)
        return e_x/torch.sum(e_x)

data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[-1].item(), 2) == 0.26
output


tensor([0.7054, 0.0351, 0.2595])

In [ ]:
#Ex 5:
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: str):
        self._grade = grade
        super().__init__(name, yob)
        ### End Code Here

    def describe(self):
        print(self._name, self._yob, self._grade )
student1 = Student(name="studentZ2023", yob=2011, grade="6")
assert student1._yob == 2011
student1.describe()


studentZ2023 2011 6


Shape of features_X: (200, 4)


Shape of features_X: (200, 4)
1.0185991537088997e-06


 individual1 :  [4.09, 4.82, -0.79, -2.41]
 individual2 :  [3.44, 2.57, 3.1, 4.02]


False


Best loss: 123415.051528805 with chromosome: [3.44, 2.57, -0.79, -2.41]
New Population: [[4.09, 4.82, 3.1, 4.02], [3.44, 2.57, -0.79, -2.41]]
Best Loss: 123415.051528805
